"""Database model helpers and BSON/JSON transformations."""
from typing import Any, Dict


def document_to_dict(doc: Dict[str, Any]) -> Dict[str, Any]:
    """Convert a MongoDB document into a JSON/Pydantic-friendly dict.
    
    Transforms ObjectId '_id' into a string 'id' and removes raw '_id'.
    """
    if not doc:
        return {}
    clean_doc = dict(doc)
    if "_id" in clean_doc:
        clean_doc["id"] = str(clean_doc.pop("_id"))
    return clean_doc


def dict_to_document(data: Dict[str, Any]) -> Dict[str, Any]:
    """Prepare a Python dict or Pydantic model dump for MongoDB insertion."""
    clean_doc = dict(data)
    # Remove 'id' if '_id' is to be generated by Mongo, or keep if present
    if "id" in clean_doc and "_id" not in clean_doc:
        clean_doc.pop("id", None)
    return clean_doc
